package io.deepstream.constants;

public enum Event {
    CONNECTION_ERROR,
    CONNECTION_STATE_CHANGED,
    ACK_TIMEOUT,
    RESPONSE_TIMEOUT,
    DELETE_TIMEOUT,
    UNSOLICITED_MESSAGE,
    MESSAGE_PARSE_ERROR,
    VERSION_EXISTS,
    NOT_AUTHENTICATED,
    LISTENER_EXISTS,
    NOT_LISTENING,
    TOO_MANY_AUTH_ATTEMPTS,
    IS_CLLOSED,
    UNKNOWN_CALLEE,
    RECORD_NOT_FOUND
}
